# Generated by Django 4.1.6 on 2023-07-08 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doceveapp', '0011_rename_courseid_assignmentsubmissionteacher_coursename_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='enrollment_id',
            new_name='enrollmentid',
        ),
    ]
