# Generated by Django 4.1.6 on 2023-07-09 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doceveapp', '0012_rename_enrollment_id_student_enrollmentid'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordsAccepted',
            fields=[
                ('enrollmentid', models.CharField(default='', max_length=70, primary_key=True, serialize=False)),
                ('studentname', models.CharField(default='', max_length=150)),
                ('batchyear', models.CharField(default='', max_length=70)),
                ('email', models.CharField(default='', max_length=150)),
                ('contactno', models.CharField(default='', max_length=70)),
                ('studentstatus', models.CharField(default='', max_length=70)),
                ('studentsem', models.CharField(default='', max_length=70)),
                ('currentstatus', models.CharField(default='', max_length=70)),
            ],
        ),
    ]
